### ISSUE TITLE
(Final) Add Ranged Skeleton Enemies

### ISSUE THREAD

**Issue by tjsg1992** [VRushLP/RigorMortisGame#22]

**Comment by VRushLP** [comment]
Halfway there!

**Comment by tjsg1992** [comment]
Is this considered done? @VRushLP

**Comment by VRushLP** [comment]
Sort of. There's a couple things about them that I would still consider wrong.

**Comment by VRushLP** [comment]
To elaborate on the previous comment, archers are massively inefficient in the way they draw arrows.
Arrows are currently drawn by rotating and translating the entire canvas. Since they never change their direction, we should instead do this once on an offscreen canvas and then save that canvas as the sprite for the arrow.
