### ISSUE TITLE
(Minimum Deliverable) Add Bat/Wisp Enemy

### ISSUE THREAD

**Issue by tjsg1992** [VRushLP/RigorMortisGame#26]

**Comment by VRushLP** [comment]
Here's a rundown of the Wisp AI:

First, wisps count down to see if they have attacked recently. More on that later.
Wisps grab the knights center point and calculate their own. Then they calculate the distance between those points. If the knight is close enough, they start chasing.
For chasing, Wisps determine the straightest path to you and then move 2px along that vector per frame (it's faster than it sounds). An if/else stops the code from dividing by 0.
If however, the Wisp has hit you recently, it backs off very quickly over the course of about a second. The path it takes is the most direct one away from you.
This causes these things to be pretty annoying pieces of shit.

One problem at the moment is that you can't actually hit these things because of the way the engine attempts to register for collision. I don't have a workaround at the moment.

**Comment by VRushLP** [comment]
Wisps fleeing from you after they touch you also helps prevent my new favorite unintended behavior.
http://puu.sh/nfHY2/bc5a72b6df.png
