### ISSUE TITLE
Visual stutter (Frame Lag)

### ISSUE THREAD

**Issue by cresse** [VRushLP/RigorMortisGame#40]
Every once in a while, the game seems to lag. Currently unsure of cause.

**Comment by VRushLP** [comment]
My gut instinct is that this is caused by the music assets, because music assets are currently unique from visual assets in two ways:
-The music assets are embedded directly into the web page
-The game does not wait for them to finish downloading before it begins to run.

My hypothesis shouldn't be too hard to test: Remove or comment out references to the music in the source code (which is currently all in main), and remove the embedded files on the webpage and see if the stutter persists.
If it isn't there anymore, then a more long term fix can simply be delaying players briefly until the necessary track is done and start downloading other tracks in the background, probably 1 at a time.
If the stutter is still there, then my hypothesis is wrong, and we'll have to dig a little deeper.

I'll open up a test branch in a few minutes.

**Comment by VRushLP** [comment]
Test branch is up. Please check it out and give it a play when you get a moment.
